This add the possibility to define minimum and maximum for Duration
yassun7010/serde_valid pull request #60
Opened 2024-04-23 13:32 UTC by StivenAigleIxxi

With the help of some crate like `serde_with`, it is possible to serialize and deserialize Duration.

With modification `serde_valid` is able to define `minimum` and `maximum` for this type. 
To define such minimum, we use the attribute validate with the parameter `minimum_duration` like this 
`#[validate(minimum_duration="10ms")]`, "10ms" is transformed into `Duration::from_millis(10)`.

We can also use `s` and `ns` prefix

2024-04-23 14:10 UTC, B14ck6u4rd requested changes

2024-04-23 14:10 UTC, B14ck6u4rd commented on serde_valid_derive/src/error.rs
> +        Self::new(lit.span(), format!("Wrong suffix found. Suffix allowed {}", suffix_allowed.iter().fold(String::new(), |acc, &arg| acc + "," + arg)))
`Self::new(lit.span(), format!("Wrong suffix found (allowed: {})", suffix_allowed.iter().fold(String::new(), |acc, &arg| acc + "," + arg)))`

2024-04-23 14:10 UTC, B14ck6u4rd commented on serde_valid/src/error.rs
> +        format!("The duration must be <= {}s", self.maximum.as_secs_f64())
`         format!("Duration must be <= {}s", self.maximum.as_secs_f64())`

2024-04-23 14:10 UTC, B14ck6u4rd commented on serde_valid/tests/complex_test.rs
> +    #[validate(maximum_duration = "60ms")]
Is it possible to have this notation ?

`#[validate(minimum_duration="15ms", maximum_duration="60ms"]`

2024-04-23 14:10 UTC, B14ck6u4rd commented on serde_valid_derive/src/attribute/field_validate/duration.rs
> +
one space-line is enough

2024-05-07 16:20 UTC, ya7010 commented
Thanks for your suggestion!

As you wrote in `lib.rs`, I would like to maintain crates' policy of supporting validation as described in jsonschema.

I think it would be better to have a helper function like `#[validate(custom(minimum_duration("10ms"))]` to clearly indicate that the validation is not a Jsonschema specification.

2024-05-13 09:09 UTC, StivenAigleIxxi commented
@yassun7010 
Is this something achievable with the current implementation of `custom`, after a brief search I think not but you know better than me. 

May be I could try to implement something like `#[validate(not_json_schema(minimum_duration("10ms")))]`, with such things, the `custom` attribute will remain a tool for the user to implement custom function. And we will have a dedicated attribute to implement, inside the library, validation that are not in json

2024-05-13 14:22 UTC, B14ck6u4rd commented
@yassun7010 @StivenAigleIxxi 

I think the `not_json_schema` is irrelevant in a crate above Serde (that can (de)serialize something other than JSON).

2024-05-13 14:55 UTC, yassun7010 commented
@StivenAigleIxxi @B14ck6u4rd

I've written my idea in https://github.com/yassun7010/serde_valid/pull/63;

What do you think? 

The way of the limitation is redundant. But, the resolution by `custom` maintains the position of this crate (based on JsonSchema).

My concern is that the JsonSchema specification will support equivalent validations in the future under different names.

2024-05-14 07:52 UTC, B14ck6u4rd commented
> @StivenAigleIxxi @B14ck6u4rd
> 
> I've written my idea in #63;
> 
> Does the method using `custom` meet your requirements?
> 
> The way of the limitation is redundant. But, the resolution by `custom` maintains the position of this crate (based on JsonSchema).
> 
> My concern is that the JsonSchema specification will support equivalent validations in the future under different names.

I very like your solution @yassun7010 !

2024-05-14 12:37 UTC, closed without merging

2024-05-14 12:45 UTC, yassun7010 commented
I released [v0.20.0](https://github.com/yassun7010/serde_valid/releases/tag/v0.20.0)

2024-05-14 13:13 UTC, B14ck6u4rd commented
Thanks for your work @yassun7010 !